import "./globals.css";
import { Header } from "@/components/Header";
import { RootLayoutProps } from "@/utils/types";

export const metadata = {
  title: "weather-app",
  description: "Generated by Juan Cruz Rodríguez",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
